# Generated by Django 3.0.2 on 2020-01-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeonstname', models.CharField(max_length=64, verbose_name='地下城名称')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '地下城',
                'verbose_name_plural': '地下城',
            },
        ),
    ]
