# Generated by Django 2.1.2 on 2020-01-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dungeons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actionstep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionstep', models.CharField(max_length=200, verbose_name='操作步骤')),
                ('type', models.CharField(max_length=200, verbose_name='操作类型')),
                ('content', models.CharField(max_length=200, verbose_name='操作内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpointname', models.CharField(max_length=200, verbose_name='关卡名称')),
                ('doordirection', models.CharField(max_length=200, verbose_name='门方向')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Dungeons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dungeons.Dungeons')),
            ],
            options={
                'verbose_name': '关卡',
                'verbose_name_plural': '关卡',
            },
        ),
        migrations.AddField(
            model_name='actionstep',
            name='Checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Checkpoint'),
        ),
    ]
