# Generated by Django 2.1.2 on 2020-02-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstep',
            name='actionNum',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='操作次数'),
        ),
        migrations.AlterField(
            model_name='actionstep',
            name='type',
            field=models.CharField(choices=[(1, '移动到'), (2, '移动'), (3, '打怪'), (4, '点击')], max_length=200, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='Dungeons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dungeons.Dungeons', verbose_name='所属副本'),
        ),
    ]
