# Generated by Django 2.2.10 on 2020-02-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0002_auto_20200227_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstep',
            name='Checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionstep_checkpoint', to='brush.Checkpoint'),
        ),
        migrations.AlterField(
            model_name='actionstep',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '移动到'), (2, '移动'), (3, '打怪'), (4, '点击')], verbose_name='操作类型'),
        ),
    ]
