# Generated by Django 3.0.6 on 2020-05-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0004_auto_20200301_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstep',
            name='actionstep',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='操作步骤'),
        ),
        migrations.AlterField(
            model_name='actionstep',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '移动到'), (2, '双击按键'), (3, '打怪'), (4, '鼠标点击'), (5, '键盘按键'), (6, '延迟')], default=1, verbose_name='操作类型'),
        ),
    ]
